version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    command: server /data

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
   minio_data:
   mongodb_data:
